### ISSUE TITLE
Add cell factory property for the dropdown list

### ISSUE THREAD

**Issue by dlemmermann** [dlsc-software-consulting-gmbh/PhoneNumberFX#3]
The field should allow the application to specify their own cell factory for the dropdown list.

**Comment by gldiazcardenas** [comment]
We already have this one: com.dlsc.phonenumberfx.PhoneNumberField#setCountryCodeViewFactory

**Comment by dlemmermann** [comment]
The previous factory only created the nodes that showed the country flags. I updated this with a cell factory for the whole cell.
