### ISSUE TITLE
Enhancement Suggestion for Flag Icon Visibility in PhoneNumberField Component

### ISSUE THREAD

**Issue by leewyatt** [dlsc-software-consulting-gmbh/PhoneNumberFX#7]
Hi Gabriel ~ I've been exploring the PhoneNumberField component and am truly impressed by its utility - great work! 

I noticed that many of the flag images contain white, which can blend with the background. 

Maybe we could discuss adding a border to enhance their distinction? Appreciate all the effort put into this component!
![image](https://github.com/dlsc-software-consulting-gmbh/PhoneNumberFX/assets/75261429/8657a195-65d4-4608-b3e9-ad582cf44154)
![image](https://github.com/dlsc-software-consulting-gmbh/PhoneNumberFX/assets/75261429/96d7be2d-ce83-4037-bf91-01fe129033b7)
![image](https://github.com/dlsc-software-consulting-gmbh/PhoneNumberFX/assets/75261429/f21fcddc-8012-4599-abf6-da47d80e2d80)

**Comment by dlemmermann** [comment]
Please follow what I did for flags shown in the list view cells.

**Comment by gldiazcardenas** [comment]
I think this issue is already fixed, right? @leewyatt ..  if it is then please close it.

**Comment by dlemmermann** [comment]
Fixed.
